In [34]:
import streamlit as st
# import folium
from PIL import Image, ExifTags
# from streamlit_folium import st_folium
import requests
import io
import cv2
import json
import numpy as np
from ultralytics import YOLO


*TEST API 1

In [23]:
my_upload=open("test2.jpg", "rb")

In [24]:
files = {"file": my_upload}
res = requests.post(url="https://wildfire-project-backend.herokuapp.com/image-detector", files=files)

In [25]:
print(res)

<Response [200]>


In [26]:
type(res)

requests.models.Response

In [27]:
status_code = res.status_code
status_ok = res.ok

print(f'The status code is {status_code}.')
print(f'The response is {status_ok}.')

The status code is 200.
The response is True.


In [28]:
res.content

b'"[[[103, 178, 246], [97, 172, 240], [90, 167, 236], [88, 165, 234], [89, 167, 238], [94, 172, 243], [92, 171, 244], [85, 164, 237], [89, 171, 243], [94, 176, 248], [89, 168, 241], [89, 169, 240], [89, 165, 237], [84, 161, 230], [89, 167, 234], [83, 159, 225], [84, 157, 219], [93, 163, 222], [92, 159, 216], [69, 133, 187], [43, 101, 153], [36, 92, 141], [58, 110, 156], [82, 134, 175], [92, 140, 182], [72, 123, 163], [64, 116, 153], [50, 105, 142], [33, 88, 125], [35, 95, 131], [50, 112, 150], [53, 111, 146], [62, 109, 137], [50, 91, 116], [32, 73, 96], [55, 96, 119], [60, 101, 124], [60, 101, 124], [43, 82, 104], [47, 86, 108], [53, 90, 110], [40, 77, 97], [42, 79, 99], [73, 110, 130], [59, 95, 113], [65, 101, 119], [52, 88, 106], [47, 83, 101], [61, 94, 113], [51, 84, 103], [51, 84, 103], [61, 94, 113], [61, 94, 113], [52, 85, 104], [52, 85, 104], [61, 94, 113], [49, 82, 101], [38, 71, 90], [46, 79, 98], [40, 73, 92], [62, 95, 114], [58, 91, 110], [63, 96, 115], [54, 88, 104], [53, 9

In [63]:
# import chardet
# chardet.detect(res.content)

{'encoding': None, 'confidence': 0.0, 'language': None}

In [22]:
# image = Image.open(io.BytesIO(res.content))
# image.show()

In [31]:
arr = np.asarray(json.loads(res.json()))  # resp.json() if using Python requests

In [37]:
type(arr)

numpy.ndarray

In [32]:
arr

array([[[103, 178, 246],
        [ 97, 172, 240],
        [ 90, 167, 236],
        ...,
        [ 28,  40,  46],
        [ 28,  39,  43],
        [ 28,  39,  43]],

       [[103, 176, 244],
        [ 96, 171, 239],
        [ 91, 166, 234],
        ...,
        [ 19,  32,  40],
        [ 19,  32,  40],
        [ 19,  33,  39]],

       [[ 95, 166, 233],
        [ 94, 168, 234],
        [ 95, 169, 235],
        ...,
        [ 14,  31,  44],
        [ 14,  31,  44],
        [ 13,  31,  42]],

       ...,

       [[ 47, 105, 164],
        [ 49, 107, 166],
        [ 49, 109, 168],
        ...,
        [ 33,  80, 132],
        [ 12,  59, 111],
        [ 34,  81, 133]],

       [[ 43, 101, 160],
        [ 46, 104, 163],
        [ 47, 107, 166],
        ...,
        [ 42,  89, 141],
        [ 17,  64, 116],
        [ 38,  85, 137]],

       [[ 41,  99, 158],
        [ 44, 102, 161],
        [ 46, 106, 165],
        ...,
        [ 41,  88, 140],
        [ 13,  60, 112],
        [ 33,  80, 132]]

In [43]:
arr1=arr.astype("uint8")

In [44]:
arr1

array([[[103, 178, 246],
        [ 97, 172, 240],
        [ 90, 167, 236],
        ...,
        [ 28,  40,  46],
        [ 28,  39,  43],
        [ 28,  39,  43]],

       [[103, 176, 244],
        [ 96, 171, 239],
        [ 91, 166, 234],
        ...,
        [ 19,  32,  40],
        [ 19,  32,  40],
        [ 19,  33,  39]],

       [[ 95, 166, 233],
        [ 94, 168, 234],
        [ 95, 169, 235],
        ...,
        [ 14,  31,  44],
        [ 14,  31,  44],
        [ 13,  31,  42]],

       ...,

       [[ 47, 105, 164],
        [ 49, 107, 166],
        [ 49, 109, 168],
        ...,
        [ 33,  80, 132],
        [ 12,  59, 111],
        [ 34,  81, 133]],

       [[ 43, 101, 160],
        [ 46, 104, 163],
        [ 47, 107, 166],
        ...,
        [ 42,  89, 141],
        [ 17,  64, 116],
        [ 38,  85, 137]],

       [[ 41,  99, 158],
        [ 44, 102, 161],
        [ 46, 106, 165],
        ...,
        [ 41,  88, 140],
        [ 13,  60, 112],
        [ 33,  80, 132]]

In [45]:
cv2.imshow("result", arr1)
cv2.waitKey(0)

-1

In [48]:
cv2.imwrite("result.jpg",arr1) #save image detected

True

In [ ]:
cv2.imread()

*TEST API OUTPUT LEVEL

In [8]:
from ultralytics import YOLO


In [9]:
model = YOLO("yolov8_run2.pt")

In [10]:
im = Image.open("test2.jpg")

In [11]:
# run trained model on uploaded image
r = model(im)



0: 384x640 1 fire, 463.0ms
Speed: 19.0ms preprocess, 463.0ms inference, 27.0ms postprocess per image at shape (1, 3, 640, 640)


In [12]:
r_plotted = r[0].plot()


In [13]:
type(r_plotted)

numpy.ndarray

In [36]:
print(r_plotted)

[[[103 178 246]
  [ 97 172 240]
  [ 90 167 236]
  ...
  [ 29  40  44]
  [ 28  40  42]
  [ 28  40  42]]

 [[103 177 243]
  [ 96 171 239]
  [ 91 166 234]
  ...
  [ 19  32  40]
  [ 19  33  39]
  [ 19  33  39]]

 [[ 93 167 231]
  [ 94 168 234]
  [ 95 169 235]
  ...
  [ 14  31  44]
  [ 15  31  43]
  [ 14  30  42]]

 ...

 [[ 47 105 164]
  [ 47 107 166]
  [ 49 109 168]
  ...
  [ 33  80 132]
  [ 12  59 111]
  [ 34  81 133]]

 [[ 43 101 160]
  [ 44 104 163]
  [ 47 107 166]
  ...
  [ 42  89 141]
  [ 17  64 116]
  [ 38  85 137]]

 [[ 41  99 158]
  [ 42 102 161]
  [ 46 106 165]
  ...
  [ 41  88 140]
  [ 13  60 112]
  [ 33  80 132]]]


In [46]:
cv2.imshow("result", r_plotted)
cv2.waitKey(0)

-1

In [10]:
cv2.imwrite("im_detected.jpg", r_plotted)

True

In [11]:
open("im_detected.jpg")

<_io.TextIOWrapper name='im_detected.jpg' mode='r' encoding='UTF-8'>

*TEST API 2

In [15]:
json.dumps(r_plotted.tolist())

'[[[103, 178, 246], [97, 172, 240], [90, 167, 236], [88, 165, 234], [89, 167, 238], [92, 171, 244], [92, 171, 244], [83, 164, 239], [89, 170, 245], [94, 176, 248], [89, 168, 241], [89, 169, 240], [88, 166, 237], [84, 161, 230], [89, 166, 235], [81, 159, 226], [85, 157, 217], [93, 163, 222], [92, 159, 216], [69, 133, 187], [43, 102, 152], [36, 92, 141], [58, 110, 156], [83, 133, 175], [92, 141, 181], [74, 123, 161], [64, 116, 153], [50, 105, 142], [31, 89, 125], [33, 95, 133], [49, 112, 150], [48, 111, 149], [68, 109, 134], [50, 91, 116], [31, 73, 96], [55, 96, 119], [60, 101, 124], [60, 101, 124], [43, 82, 104], [47, 86, 108], [51, 90, 112], [40, 77, 97], [42, 79, 99], [73, 110, 130], [59, 95, 113], [65, 101, 119], [52, 88, 106], [47, 83, 101], [61, 94, 113], [51, 84, 103], [51, 84, 103], [61, 94, 113], [61, 94, 113], [52, 85, 104], [52, 85, 104], [61, 94, 113], [49, 82, 101], [38, 71, 90], [46, 79, 98], [40, 73, 92], [62, 95, 114], [58, 91, 110], [63, 96, 115], [54, 87, 106], [53, 91,